defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  num_hidden_layers_mog_net: 10
  hidden_layer_dim: 256
  n_mixtures: 18
  residuals: True
  weight_decay: 1e-7

logger_config:
  experiment_name: TEST
  run_name: MADEMOG
  model_name: Higgs_MADEMOG
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 20

trainer_config: 
  gpus: 1 
  max_epochs: 301
  num_sanity_val_steps: 0