defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 1e-4
  activation: ReLU
  num_flows: 10
  num_hidden_layers: 2
  hidden_layer_dim: 128
  batchnorm_flow: True
  maf_residuals: True
  conv1x1: True
  weight_decay: 1e-7

  # lr_scheduler_dct: {"scheduler": "ExponentialLR", "interval": "step", "params": {"gamma": 0.9995}}
  
  use_mog: True
  residuals: False
  num_hidden_layers_mog_net: 4
  n_mixtures: 10
  
logger_config:
  experiment_name: TEST
  run_name: higgs_MAFMADE
  model_name: MAFMADE
  early_stop_dict: 
    monitor: train_loss
    mode: min
    patience: 101

trainer_config: 
  gpus: 1
  max_epochs: 101
  num_sanity_val_steps: 0