defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  num_flows: 10
  num_hidden_layers: 2
  hidden_layer_dim: 128
  weight_decay: 1e-7

  # lr_scheduler_dct: {"scheduler": "CosineAnnealingLR", "interval": "step", "params": {"T_max": 1000, "eta_min": 1e-6}}
  # lr_scheduler_dct: {"scheduler": "ExponentialLR", "interval": "step", "params": {"gamma": 0.9999}}

  spline_type: quadratic
  batchnorm_flow: True
  conv1x1: False
  
  u_net: False
  resnet: True
  ar: True
  bins: 12
  tail_bound: 5.0
  
logger_config:
  experiment_name: TEST
  run_name: PolySplines
  model_name: higgs_polynomial_splines
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 40

trainer_config: 
  gpus: 1
  max_epochs: 101
  num_sanity_val_steps: 0
  gradient_clip_val: 5.0