defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  num_flows: 10
  num_hidden_layers: 3
  hidden_layer_dim: 128
  batchnorm: False
  batchnorm_flow: True
  use_masks: False
  weight_decay: 1e-7
  
logger_config:
  experiment_name: TEST
  run_name: Higgs_RealNVP
  model_name: RealNVP
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 15

trainer_config: 
  gpus: 1
  max_epochs: 201
  num_sanity_val_steps: 0