defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  num_flows: 10
  num_hidden_layers: 2
  hidden_layer_dim: 128
  weight_decay: 1e-7

  batchnorm_flow: True
  conv1x1: True
  
  u_net: False
  resnet: True
  ar: True
  bins: 10
  tail_bound: 5.0
  
logger_config:
  experiment_name: TEST
  run_name: RqSplines
  model_name: Higgs_rq_splines
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 101

trainer_config: 
  gpus: 1
  max_epochs: 101
  num_sanity_val_steps: 0
  gradient_clip_val: 5.0