defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 1e-3
  activation: ReLU
  latent_dim: 18
  output_activation: Identity
  weight_decay: 1e-7

  hidden_layers: [128, 128, 128]

  use_resnet: True
  encoder_layers: 128
  encoder_deepths: 5
  decoder_layers: 128
  decoder_deepths: 5

logger_config:
  experiment_name: TEST
  run_name: VAE
  model_name: Higgs_VAE
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 10

trainer_config: 
  gpus: 1 
  max_epochs: 51
  num_sanity_val_steps: 0
