model_name: rqsplines

activation: ReLU
num_flows: 10
num_hidden_layers: 2
hidden_layer_dim: 512
batchnorm_flow: True
conv1x1: True
res_layers_in_block: 2
normalization_out: True

u_net: False
resnet: True
ar: True

bins: 32
tail_bound: 5.0
