experiment_config:
  experiment_name: null
  run_name: null
  model_postfix: null
  save_dir: ./mlruns

  seed: 0
  accelerator: gpu
  device: cuda
  precision: 32-true
  devices: 1

  log_every_n_steps: 10
  check_eval_n_epoch: 1
  num_sanity_val_steps: 0
  check_metrics_n_epoch: 10
