defaults:
  - _self_
  - data_config
  - training_config
  - experiment_config
  - model_config: made_mog
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
